name: test_node_github_action_2

on: 
  push:
    branches: 
      - test_action

jobs:
  Test_GitHub_Actions :
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm test

  the_merge :
      - needs: Test_GitHub_Actions
      - name: merge
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: master
          github_token: ${{ secrets.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 }}

# faire une 2e branche : quand on push dessus, ça doit déclencher la CI, et le GitHub Action doit exécuter les tests, et si les tests sont bons, merge ta branche